version: '3.8'

services:
  # 1. OpenTripPlanner (バックエンド)
  otp:
    build: ./otp
    container_name: otp
    environment:
      - JAVA_OPTS=-Xmx8G
    ports:
      - "8080:8080"
    # volumes:
    #   - ./otp/graph:/var/otp/graphs/default
    command: ["java", "-jar", "/app/otp-1.5.0-shaded.jar", "--build", "/var/otp/graphs/default", "--inMemory", "--analyst"]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - otp